export const SET_BACKGROUND = "SET_BACKGROUND";
export const RESET_BACKGROUND = "RESET_BACKGROUND";


export const SET_CANDIDATES = "SET_CANDIDATES";

export const CLEAR_CANDIDATES = "CLEAR_CANDIDATES";

